/*
 * servo_pins.h
 */

#ifndef __SERVO_PINS_H
#define __SERVO_PINS_H

#define BIT_SERVO0 LATBbits.LATB15
#define BIT_SERVO1 LATBbits.LATB14
#define BIT_SERVO2 LATBbits.LATB13
#define BIT_SERVO3 LATBbits.LATB12
#define BIT_SERVO4 LATBbits.LATB11
#define BIT_SERVO5 LATBbits.LATB10
#define BIT_SERVO6 LATBbits.LATB9
#define BIT_SERVO7 LATBbits.LATB8
#define BIT_SERVO8 LATBbits.LATB7
#define BIT_SERVO9 LATBbits.LATB6

#define DIR_SERVO0 TRISBbits.TRISB15
#define DIR_SERVO1 TRISBbits.TRISB14
#define DIR_SERVO2 TRISBbits.TRISB13
#define DIR_SERVO3 TRISBbits.TRISB12
#define DIR_SERVO4 TRISBbits.TRISB11
#define DIR_SERVO5 TRISBbits.TRISB10
#define DIR_SERVO6 TRISBbits.TRISB9
#define DIR_SERVO7 TRISBbits.TRISB8
#define DIR_SERVO8 TRISBbits.TRISB7
#define DIR_SERVO9 TRISBbits.TRISB6

#define OPEN_DRAIN_SERVO0 ODCBbits.ODCB15
#define OPEN_DRAIN_SERVO1 ODCBbits.ODCB14
#define OPEN_DRAIN_SERVO2 ODCBbits.ODCB13
#define OPEN_DRAIN_SERVO3 ODCBbits.ODCB12
#define OPEN_DRAIN_SERVO4 ODCBbits.ODCB11
#define OPEN_DRAIN_SERVO5 ODCBbits.ODCB10
#define OPEN_DRAIN_SERVO6 ODCBbits.ODCB9
#define OPEN_DRAIN_SERVO7 ODCBbits.ODCB8
#define OPEN_DRAIN_SERVO8 ODCBbits.ODCB7
#define OPEN_DRAIN_SERVO9 ODCBbits.ODCB6

#define init_servo_pins() { \
    OPEN_DRAIN_SERVO0 = 1;\
    OPEN_DRAIN_SERVO1 = 1;\
    OPEN_DRAIN_SERVO2 = 1;\
    OPEN_DRAIN_SERVO3 = 1;\
    OPEN_DRAIN_SERVO4 = 1;\
    OPEN_DRAIN_SERVO5 = 1;\
    OPEN_DRAIN_SERVO6 = 1;\
    OPEN_DRAIN_SERVO7 = 1;\
    OPEN_DRAIN_SERVO8 = 1;\
    OPEN_DRAIN_SERVO9 = 1;\
    \
    DIR_SERVO0 = PORT_OUT;\
    DIR_SERVO1 = PORT_OUT;\
    DIR_SERVO2 = PORT_OUT;\
    DIR_SERVO3 = PORT_OUT;\
    DIR_SERVO4 = PORT_OUT;\
    DIR_SERVO5 = PORT_OUT;\
    DIR_SERVO6 = PORT_OUT;\
    DIR_SERVO7 = PORT_OUT;\
    DIR_SERVO8 = PORT_OUT;\
    DIR_SERVO9 = PORT_OUT;\
    \
    BIT_SERVO0 = 0;\
    BIT_SERVO1 = 0;\
    BIT_SERVO2 = 0;\
    BIT_SERVO3 = 0;\
    BIT_SERVO4 = 0;\
    BIT_SERVO5 = 0;\
    BIT_SERVO6 = 0;\
    BIT_SERVO7 = 0;\
    BIT_SERVO8 = 0;\
    BIT_SERVO9 = 0;\
    }

#endif
